### ISSUE TITLE
Block Quotes

### ISSUE THREAD

**Issue by lsnovich** [avichazen/avi-chazen#5]
I don't think it was intentional that your text is in a blockquote
![Screenshot from 2020-09-29 15-40-29](https://user-images.githubusercontent.com/38726461/94559616-2fff9500-026a-11eb-802f-1067b38ac919.png)
the grey line appears when you insert a space at the head of the line. 
If this is intentional, let me know. 
If not, remove the trailing space and it should render properly

**Comment by avichazen** [comment]
I did intend this but when I look at it again, it does look weird so I took
it out

**Comment by lsnovich** [comment]
I am still seeing the issue
there are 2 ways to make a block quote

on purpose 
> with a bracket 

so if this ^^ is not what you wanted remove the ``>`` in your markdown

or in some cases by accident
 by creating a space before the text in the line, but with Github I don't think this happens

**Comment by avichazen** [comment]
I meant it close this as it has been resolved
